[package]
name = "queue_bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nolock = "0.3.1"
lockfree = "0.5.1"
rtrb = "0.2.0"
threadpool = "1.8.1"